networks:
  laravel-docker-network:  
      driver: bridge  

volumes:
  laravel-docker-volume:  
      driver: local 

services:
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
        - 80:80
        - 443:443
    volumes: 
        - ./:/var/www/html:cached
        - ./.docker/nginx:/etc/nginx/conf.d
        - ./.docker/nginx/ssl:/etc/nginx/conf.d/ssl
    depends_on: 
        - php
    networks: 
        - laravel-docker-network
      
  php:
    build:
       context: ./.docker/php
       dockerfile: DockerFile 
    container_name: laravel-php     
    restart: unless-stopped
    tty: true
    volumes:
       - ./:/var/www/html:cached
       - ./.docker/php/php-fpm.ini:/user/local/etc/php/conf.d/custom.ini
       - ~/.ssh:/root/.ssh
    depends_on: 
        - mysql
        - redis   
    networks: 
      - laravel-docker-network   

  mysql:    
    image: mysql:latest
    container_name: laravel-mysql
    restart: unless-stopped
    ports:
       - "3306:3306"
    volumes:
       - ./data/mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE : laravel_test_database
       MYSQL_USER : laravel_test_database_user
       MYSQL_PASSWORD : secret
       MYSQL_ROOT_PASSWORD : secret   
    networks: 
      - laravel-docker-network

  redis:
    image: redis:alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
       - 6380:6379
    volumes:
       - ./data/redis:/data  
    networks: 
      - laravel-docker-network   

  composer: 
    image: composer:latest
    container_name: laravel-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install", "--ignore-platform-reqs"]
    depends_on:
      - php
    networks:
      - laravel-docker-network

  artisan:
    build:
      context: ./.docker/php
      dockerfile: DockerFile 
    container_name: laravel-artisan
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel-docker-network   

  npm:
    image: node:latest
    container_name: laravel-npm
    volumes:
      - ./:/var/www//html
    working_dir: /var/www/html
    entrypoint: ["npm"]  
    networks:
      - laravel-docker-network                  