networks:
  laravel:
      name: laravel  
      driver: bridge  

services:
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    tty: true
    ports:
        - "80:80"
        - "443:443"
    volumes: 
        - ./src:/var/www/html:cached
        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
        - php
        - mysql
    networks: 
        - laravel
      
  php:
    build:
       context: .
       dockerfile: DockerFile 
    container_name: laravel_php     
    restart: unless-stopped
    tty: true
    volumes:
       - ./src:/var/www/html
    networks: 
      - laravel   

  mysql:    
    image: mysql:latest
    container_name: laravel_mysql
    ports:
       - 3306:3306
    volumes:
       - ./mysql:/var/lib/mysql
    environment:
       MYSQL_DATABASE : laravel_test_database
       MYSQL_USER : laravel_test_database_user
       MYSQL_PASSWORD : secret
       MYSQL_ROOT_PASSWORD : secret   
    networks: 
      - laravel   

  composer: 
    image: composer:latest
    container_name: laravel_composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install", "--ignore-platform-reqs"]
    depends_on:
      - php
    networks:
      - laravel

  artisan:
    build:
      context: .
      dockerfile: DockerFile
    container_name: laravel_artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["php", "artisan"]
    networks:
      - laravel                  