FROM php:8.3-fpm-alpine

ADD ./php/www.conf /user/local/etc/php-fpm.d/www.conf

RUN addgroup -g 1000 laravel && adduser -G laravel -s /bin/sh -D laravel

RUN mkdir -p /var/www/html

WORKDIR /var/www/html

# Install requred packages for composer
RUN apk update && apk add --no-cache \
    curl \
    zip \
    unzip \
    libzip-dev \
    zlib-dev \
    libjpeg-turbo-dev \
    freetype-dev \
    oniguruma-dev \
    build-base

RUN docker-php-ext-install pdo pdo_mysql mbstring exif pcntl bcmath gd zip

RUN docker-php-ext-configure gd --with-jpeg --with-freetype

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer

RUN chown -R laravel:laravel /var/www/html

USER laravel
